import { Rubik } from 'next/font/google';
import Navbar from '../components/navbar/navbar';
import './globals.css';

export const metadata = {
  title: 'CRYPTO GURU DEALS',
  description: 'Generated by create next app',
}
const inter = Rubik({ subsets: ['latin'] })
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
